apiVersion: v1
kind: Namespace
metadata:
  name: bu-created-namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: bu-team
  name: bu-created-sa
  namespace: bu-created-namespace
